name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test with Code Coverage
      run: dotnet test --no-build --verbosity normal -- --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml --filter-not-class "*SchemeOwnerIntegrationTests" --filter-not-class "*IntegrationTests" --filter-not-class "*SatelliteServiceTests"
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: '**/TestResults/coverage.cobertura.xml'
