name: Publish to NuGet

on:
  release:
    types: [published]
      
jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release -- --filter-not-class "*SchemeOwnerIntegrationTests" --filter-not-class "*IntegrationTests" --filter-not-class "*SatelliteServiceTests"
    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      with:
        nuget-version: latest
        nuget-api-key: ${{secrets.NUGET_API_KEY}}
    - name: Extract version
      run: |
        VERSION=${{github.event.release.tag_name}}
        echo "VERSION=${VERSION:1}" >> $GITHUB_ENV
    - name: Pack package
      run: dotnet pack Poort8.Ishare.Core/Poort8.Ishare.Core.csproj --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -p:PackageVersion=${{env.VERSION}}
    - name: Publish to NuGet
      run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
    - uses: actions/upload-artifact@v4
      name: Publish to GitHub
      with:
        name: Poort8.Ishare.Core.${{github.event.release.tag_name}}
        path: "**/*.nupkg"
